language: python
# python versions to use during the tests
python:
    - "3.6"
# command to install dependencies
install:
    - pip install -r requirements.txt
# command to run tests
script:
    - py.test --cov blockchain tests --cov-report term-missing
branches:
  only:
   - master
after_success:
    - coveralls
after_failure:
    - coveralls